import { TimestampDto } from './timestamp.dto';
import { UserDetailDto, UserDto } from './user.dto';
import { MunicipalityDto } from './municipality.dto';
import { IdentificationTypeDto } from './identificationTypeDto';
import { GenderDto } from './gender.dto';

export interface PeopleDto extends TimestampDto {
  id: number;
  avatarResume: string;
  institutionId: number;
  userId: number;
  identification: string;
  identificationTypeId: number;
  identificationTypeName: string;
  names: string;
  lastnames: string;
  mobile: string;
  email: string;
  homeMunicipalityId: number;
  homeMunicipality: MunicipalityDto;
  direction: string;
  birthDate: string;
  birthMunicipalityId: number;
  birthMunicipality: MunicipalityDto;
  genderId: number;
  workPhone: string;
  homePhone: string;
  nationality: string;
  religion: string;
  primaryLanguage: string;
  user?: UserDto;
  outputContactNameOne: string;
  outputContactPhoneOne: string;
  outputContactNameTwo: string;
  outputContactPhoneTwo: string;
}

export interface PeopleDetailDto extends TimestampDto {
  id: number;
  institutionId: number;
  userId: number;
  lmsUserKey: any;
  identification: string;
  identificationTypeId: number;
  identificationMunicipalityId: number;
  firstName: string;
  secondName: string;
  firstLastname: string;
  secondLastname: string;
  names: string;
  lastnames: string;
  mobile: string;
  homePhone: string;
  workPhone: string;
  email: string;
  homeMunicipalityId: number;
  direction: string;
  birthDate: string;
  birthMunicipalityId: number;
  nationality: string;
  genderId: number;
  religion: string;
  primaryLanguage: string;
  relation: string;
  scholarshipTypeId: number;
  zone: string;
  schoolInsuranceId: number;
  observations: string;
  outputContactNameOne: string;
  outputContactPhoneOne: string;
  outputContactNameTwo: string;
  outputContactPhoneTwo: string;
  enrollmentDate: string;
  companyName: string;
  companyPosition: string;
  alternateEmail: string;
  companyAreaId: number;
  isACollaborator: number;
  homeMunicipality: MunicipalityDto;
  birthMunicipality: MunicipalityDto;
  identificationType: IdentificationTypeDto;
  gender: GenderDto;
}

export interface PeopleWithUserDto extends TimestampDto {
  id: number;
  institutionId: number;
  userId: number;
  lmsUserKey: string;
  identification: string;
  identificationTypeId: number;
  identificationMunicipalityId: number;
  firstName: string;
  secondName: string;
  firstLastname: string;
  secondLastname: string;
  names: string;
  lastnames: string;
  mobile: string;
  homePhone: string;
  workPhone: string;
  email: string;
  homeMunicipalityId: number;
  direction: string;
  birthDate: string;
  birthMunicipalityId: number;
  nationality: string;
  genderId: number;
  religion: string;
  primaryLanguage: string;
  relation: string;
  scholarshipTypeId: number;
  zone: string;
  schoolInsuranceId: number;
  observations: string;
  outputContactOne: string;
  outputContactTwo: string;
  enrollmentDate: string;
  companyName: string;
  companyPosition: string;
  alternateEmail: string;
  companyAreaId: number;
  isACollaborator: number;
  user: UserDetailDto;
}
