import { App } from 'vue';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faHome,
  faBars,
  faExpand,
  faUserCircle,
  faSignOutAlt,
  faEye,
  faEyeSlash,
  faExclamationTriangle,
  faUserFriends,
  faClipboardList,
  faCalendarMinus,
  faBuilding,
  faBookOpen,
  faGraduationCap,
  faChartLine,
  faCalendarWeek,
  faUsers,
  faShoppingCart,
  faSearch,
  faFilter,
  faSignInAlt,
  faPlus,
  faKey,
  faPencilAlt,
  faTrash,
  faWindowClose,
  faPoll,
  faUser,
  faFileMedical,
  faHouseUser,
  faSchool,
  faArrowCircleUp,
  faCalendar,
  faTasks,
  faAddressCard,
  faBan,
  faLayerGroup,
  faChartBar,
  faShoppingBag,
  faExclamationCircle,
  faTable,
  faTags,
  faReceipt,
  faUniversity,
  faDollarSign,
  faUserCog,
  faAngleDown,
  faCreditCard,
  faMoneyBill,
  faArrowsAlt,
  faCheck,
  faTimes,
  faFileSignature,
  faInfo,
  faBook,
  faCloudDownloadAlt,
  faCloudUploadAlt,
  faFolderOpen,
  faCheckCircle,
  faSync,
  faEnvelope,
  faFile,
  faCog,
  faUserPlus,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faCaretDown,
  faCaretUp,
  faCircleNotch,
  faEdit,
  faUserMinus,
  faExternalLinkAlt,
  faBookmark,
  faFileAlt,
  faSlidersH,
  faClock,
  faClipboardCheck,
  faUpload,
  faTh,
  faSyncAlt,
  faComments,
  faBackward,
  faForward,
  faBookMedical,
  faAngleLeft,
  faAngleRight,
  faCalendarAlt,
  faThumbsUp,
  faThumbsDown,
  faFileInvoiceDollar,
  faPaperclip,
  faCopy,
  faPercentage,
  faPaperPlane,
  faTimesCircle,
  faCommentAlt,
  faBullhorn,
  faInfoCircle,
  faImage,
  faStarHalfAlt,
  faBell,
  faPhoneSquareAlt,
  faMinusSquare,
  faMinusCircle,
  faMoneyCheckAlt,
  faWallet,
  faUserSecret,
  faCogs,
  faCircle,
  faHeart,
  faCar,
  faTools,
  faSitemap,
  faChalkboard,
  faChalkboardTeacher,
  faUsersCog,
  faFilePowerpoint,
  faMinus,
  faCheckSquare,
  faSquare,
  faNewspaper,
  faHandPaper,
  faArrowUp,
  faArrowDown,
  faUndo,
  faFileContract,
  faCheckDouble,
  faList,
  faQuestionCircle,
  faUserEdit,
  faUserTie,
  faUnlockAlt,
  faMicrophone,
  faMicrophoneSlash,
  faCompress,
  faLongArrowAltRight,
  faEllipsisV,
  faFileDownload,
  faScroll,
  faCertificate,
  faAward,
  faTrophy,
  faHandshake,
  faLink,
  faCode,
  faPalette,
  faFont,
  faUnlock,
  faSearchMinus,
  faSearchPlus,
  faRedo,
  faBold,
  faItalic,
  faUnderline,
  faStrikethrough,
  faAlignLeft,
  faCalculator,
  faDatabase,
  faGlobe,
  faShieldAlt,
  faBriefcase,
  faIdBadge,
  faMapMarkerAlt,
  faDesktop,
  faPlayCircle,
  faChartPie,
  faCamera,
  faQrcode,
  faArrowLeft,
  faDownload,
  faFilePdf,
  faPrint,
  faHashtag,
  faCalendarTimes,
  faStar,
  faChartArea,
  faBullseye,
  faWifi,
  faWind,
  faBox,
  faFolder,
  faPowerOff,
  faProjectDiagram,
  faSave,
  faIdCard,
  faPen,
  faPhone,
  faBalanceScale,
  faMedal,
  faHistory,
  faExclamation,
  faLanguage,
  faAlignCenter,
  faAlignRight,
  faAlignJustify,
  faComment,
  faCalendarCheck,
  faVideo,
  faUserSlash,
  faMobileAlt,
  faTabletAlt,
  faFileCode,
  faLock,
  faTag,
  faHeartbeat,
  faRunning,
  faBrain,
  faGripVertical,
  faStream,
  faDoorOpen,
  faUserCheck,
  faRobot,
  faMagic,
  faArrowRight,
  faListAlt,
  faFlag,
  faFlagCheckered,
  faAdjust,
} from '@fortawesome/free-solid-svg-icons';
export default {
  install: (app: App) => {
    library.add(faHome);
    library.add(faBars);
    library.add(faExpand);
    library.add(faUserCircle);
    library.add(faSignOutAlt);
    library.add(faEye);
    library.add(faEyeSlash);
    library.add(faShoppingCart);
    library.add(faSearch);
    library.add(faFilter);
    library.add(faExclamationTriangle);
    library.add(faUserFriends);
    library.add(faClipboardList);
    library.add(faCalendarMinus);
    library.add(faBuilding);
    library.add(faBookOpen);
    library.add(faGraduationCap);
    library.add(faChartLine);
    library.add(faCalendarWeek);
    library.add(faUsers);
    library.add(faSignInAlt);
    library.add(faPlus);
    library.add(faKey);
    library.add(faPencilAlt);
    library.add(faTrash);
    library.add(faWindowClose);
    library.add(faPoll);
    library.add(faUser);
    library.add(faFileMedical);
    library.add(faHouseUser);
    library.add(faSchool);
    library.add(faArrowCircleUp);
    library.add(faCalendar);
    library.add(faTasks);
    library.add(faAddressCard);
    library.add(faBan);
    library.add(faLayerGroup);
    library.add(faChartBar);
    library.add(faShoppingBag);
    library.add(faExclamationCircle);
    library.add(faTable);
    library.add(faTags);
    library.add(faReceipt);
    library.add(faUniversity);
    library.add(faDollarSign);
    library.add(faUserCog);
    library.add(faAngleDown);
    library.add(faCreditCard);
    library.add(faMoneyBill);
    library.add(faArrowsAlt);
    library.add(faCheck);
    library.add(faTimes);
    library.add(faFileSignature);
    library.add(faInfo);
    library.add(faBook);
    library.add(faCloudDownloadAlt);
    library.add(faCloudUploadAlt);
    library.add(faFolderOpen);
    library.add(faCheckCircle);
    library.add(faSync);
    library.add(faEnvelope);
    library.add(faFile);
    library.add(faCog);
    library.add(faChevronLeft);
    library.add(faChevronRight);
    library.add(faUserPlus);
    library.add(faCaretUp);
    library.add(faCaretDown);
    library.add(faCircleNotch);
    library.add(faEdit);
    library.add(faUserMinus);
    library.add(faExternalLinkAlt);
    library.add(faFileAlt);
    library.add(faBookmark);
    library.add(faSlidersH);
    library.add(faClock);
    library.add(faClipboardCheck);
    library.add(faUpload);
    library.add(faTh);
    library.add(faSyncAlt);
    library.add(faComments);
    library.add(faForward);
    library.add(faBackward);
    library.add(faBookMedical);
    library.add(faAngleLeft);
    library.add(faAngleRight);
    library.add(faCalendarAlt);
    library.add(faThumbsUp);
    library.add(faThumbsDown);
    library.add(faFileInvoiceDollar);
    library.add(faPaperclip);
    library.add(faCopy);
    library.add(faPercentage);
    library.add(faPaperPlane);
    library.add(faTimesCircle);
    library.add(faCommentAlt);
    library.add(faBullhorn);
    library.add(faInfoCircle);
    library.add(faImage);
    library.add(faStarHalfAlt);
    library.add(faBell);
    library.add(faPhoneSquareAlt);
    library.add(faMinusSquare);
    library.add(faMinusCircle);
    library.add(faMoneyCheckAlt);
    library.add(faWallet);
    library.add(faUserSecret);
    library.add(faCogs);
    library.add(faCircle);
    library.add(faHeart);
    library.add(faCar);
    library.add(faTools);
    library.add(faSitemap);
    library.add(faChalkboard);
    library.add(faChalkboardTeacher);
    library.add(faUsersCog);
    library.add(faFilePowerpoint);
    library.add(faMinus);
    library.add(faCheckSquare);
    library.add(faSquare);
    library.add(faNewspaper);
    library.add(faHandPaper);
    library.add(faArrowUp);
    library.add(faArrowDown);
    library.add(faUndo);
    library.add(faFileContract);
    library.add(faCheckDouble);
    library.add(faList);
    library.add(faQuestionCircle);
    library.add(faUserEdit);
    library.add(faUserTie);
    library.add(faChevronDown);
    library.add(faChevronUp);
    library.add(faUnlockAlt);
    library.add(faMicrophone);
    library.add(faMicrophoneSlash);
    library.add(faCompress);
    library.add(faLongArrowAltRight);
    library.add(faEllipsisV);
    library.add(faFileDownload);
    library.add(faScroll);
    library.add(faCertificate);
    library.add(faAward);
    library.add(faTrophy);
    library.add(faHandshake);
    library.add(faLink);
    library.add(faCode);
    library.add(faPalette);
    library.add(faFont);
    library.add(faUnlock);
    library.add(faSearchMinus);
    library.add(faSearchPlus);
    library.add(faRedo);
    library.add(faBold);
    library.add(faItalic);
    library.add(faUnderline);
    library.add(faStrikethrough);
    library.add(faAlignLeft);
    library.add(faCalculator);
    library.add(faDatabase);
    library.add(faGlobe);
    library.add(faShieldAlt);
    library.add(faBriefcase);
    library.add(faIdBadge);
    library.add(faMapMarkerAlt);
    library.add(faDesktop);
    library.add(faPlayCircle);
    library.add(faChartPie);
    library.add(faCamera);
    library.add(faQrcode);
    library.add(faArrowLeft);
    library.add(faDownload);
    library.add(faFilePdf);
    library.add(faPrint);
    library.add(faHashtag);
    library.add(faCalendarTimes);
    library.add(faStar);
    library.add(faChartArea);
    library.add(faBullseye);
    library.add(faWifi);
    library.add(faWind);
    library.add(faBox);
    library.add(faFolder);
    library.add(faPowerOff);
    library.add(faProjectDiagram);
    library.add(faSave);
    library.add(faIdCard);
    library.add(faPen);
    library.add(faPhone);
    library.add(faBalanceScale);
    library.add(faMedal);
    library.add(faHistory);
    library.add(faExclamation);
    library.add(faLanguage);
    library.add(faAlignCenter);
    library.add(faAlignRight);
    library.add(faAlignJustify);
    library.add(faComment);
    library.add(faCalendarCheck);
    library.add(faVideo);
    library.add(faUserSlash);
    library.add(faMobileAlt);
    library.add(faTabletAlt);
    library.add(faFileCode);
    library.add(faLock);
    library.add(faTag);
    library.add(faHeartbeat);
    library.add(faRunning);
    library.add(faBrain);
    library.add(faGripVertical);
    library.add(faStream);
    library.add(faDoorOpen);
    library.add(faUserCheck);
    library.add(faRobot);
    library.add(faMagic);
    library.add(faArrowRight);
    library.add(faListAlt);
    library.add(faFlag);
    library.add(faFlagCheckered);
    library.add(faAdjust);

    app.component('font-awesome-icon', FontAwesomeIcon);
  },
};
